#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 19 14:42:28 2026

@author: geoffreydesena

Exercise 3b: matplotlib example

The following code was generated by ChatGPT with the following prompt:
    
Prompt
------
I have a dictionary of dataframes that looks like the example below:

[df header]

where 'wp5' indicates the wind penetration level, and v_char indicates a characteristic wind speed. We can ignore the other columns for the current task. These data are saved in a pickle called "hourly_windspeeds_by_wp.pkl". 

I also have a dataframe pickled as "Pload_series.pkl". Extracting these data into a dataframe looks like this:

[df header]

where RT_Demand is the real time system demand in MW. 

The two data sets overlap for four years of hourly measurements. I want to create a scatter plot of the data with v_char on the x axis (only the data from wp5) and RT_Demand on the y axis (rename to P_load). I also want there to be histograms of the data on both the x and y axes. Here's an example from matplotlib that utilizes subplot_mosaic to plot the histograms beside the scatter.

[example code from matplotlib]

Provide the code for a plot similar to the example plot using my v_char and P_load data.
-------------------

Chat gave me a perfectly functioning script, but I wanted something I could run
from the other script, so I asked it to make the code more modular and able
to be imported and run from another script.

Here is the result:

"""
import pandas as pd
import matplotlib.pyplot as plt


def load_wind_data(wind_pickle_path):
    """
    Load the dictionary of wind dataframes from pickle.

    Parameters
    ----------
    wind_pickle_path : str
        Path to the pickle containing the wind dataframe dictionary.

    Returns
    -------
    dict
        Dictionary of dataframes keyed by wind penetration level.
    """
    return pd.read_pickle(wind_pickle_path)


def load_pload_data(pload_pickle_path, demand_col="RT_Demand"):
    """
    Load the load dataframe from pickle and return a cleaned P_load series.

    Parameters
    ----------
    pload_pickle_path : str
        Path to the pickle containing the load dataframe.
    demand_col : str, default "RT_Demand"
        Name of the demand column in the dataframe.

    Returns
    -------
    pandas.Series
        Load series named 'P_load' with datetime index.
    """
    pload_df = pd.read_pickle(pload_pickle_path)

    pload = pload_df[demand_col].copy()
    pload.index = pd.to_datetime(pload.index)
    pload.name = "P_load"

    return pload


def extract_vchar_series(wind_data_dict, wp_key="wp5", vchar_col="v_char"):
    """
    Extract the v_char series from a selected wind penetration dataframe.

    Parameters
    ----------
    wind_data_dict : dict
        Dictionary of wind dataframes.
    wp_key : str, default "wp5"
        Key for the desired wind penetration level.
    vchar_col : str, default "v_char"
        Name of the characteristic wind speed column.

    Returns
    -------
    pandas.Series
        v_char series with datetime index.
    """
    df_wp = wind_data_dict[wp_key].copy()
    vchar = df_wp[vchar_col].copy()
    vchar.index = pd.to_datetime(vchar.index)
    vchar.name = "v_char"

    return vchar


def align_vchar_and_pload(vchar, pload):
    """
    Align v_char and P_load series on overlapping timestamps.

    Parameters
    ----------
    vchar : pandas.Series
        Characteristic wind speed series.
    pload : pandas.Series
        Load series.

    Returns
    -------
    pandas.DataFrame
        Dataframe with columns ['v_char', 'P_load'] containing overlapping data only.
    """
    df_plot = pd.concat([vchar, pload], axis=1, join="inner").dropna()
    df_plot.columns = ["v_char", "P_load"]
    return df_plot


def scatter_hist(x, y, ax, ax_histx, ax_histy, bins_x=40, bins_y=40,
                 scatter_kwargs=None, histx_kwargs=None, histy_kwargs=None):
    """
    Draw a scatter plot with marginal histograms.

    Parameters
    ----------
    x, y : array-like
        Data for the scatter plot.
    ax : matplotlib.axes.Axes
        Main scatter axis.
    ax_histx : matplotlib.axes.Axes
        Top histogram axis.
    ax_histy : matplotlib.axes.Axes
        Right histogram axis.
    bins_x, bins_y : int, default 40
        Number of bins for x and y histograms.
    scatter_kwargs, histx_kwargs, histy_kwargs : dict or None
        Optional keyword arguments passed to plotting calls.
    """
    scatter_kwargs = scatter_kwargs or {"s": 8, "alpha": 0.35}
    histx_kwargs = histx_kwargs or {}
    histy_kwargs = histy_kwargs or {}

    ax_histx.tick_params(axis="x", labelbottom=False)
    ax_histy.tick_params(axis="y", labelleft=False)

    ax.scatter(x, y, **scatter_kwargs)
    ax_histx.hist(x, bins=bins_x, **histx_kwargs)
    ax_histy.hist(y, bins=bins_y, orientation="horizontal", **histy_kwargs)


def create_scatter_hist_figure(df_plot, bins_x=40, bins_y=40, figsize=(8, 8),
                               title="v_char vs P_load (overlapping hourly data)"):
    """
    Create the scatter + marginal histogram figure.

    Parameters
    ----------
    df_plot : pandas.DataFrame
        Dataframe with columns ['v_char', 'P_load'].
    bins_x, bins_y : int, default 40
        Number of bins for x and y histograms.
    figsize : tuple, default (8, 8)
        Figure size.
    title : str
        Plot title.

    Returns
    -------
    fig : matplotlib.figure.Figure
    axs : dict
        Dictionary of axes from subplot_mosaic.
    """
    fig, axs = plt.subplot_mosaic(
        [['histx', '.'],
         ['scatter', 'histy']],
        figsize=figsize,
        width_ratios=(4, 1.2),
        height_ratios=(1.2, 4),
        layout="constrained"
    )

    scatter_hist(
        df_plot["v_char"],
        df_plot["P_load"],
        axs["scatter"],
        axs["histx"],
        axs["histy"],
        bins_x=bins_x,
        bins_y=bins_y
    )

    axs["scatter"].set_xlabel("v_char")
    axs["scatter"].set_ylabel("P_load")
    axs["histx"].set_title(title)

    return fig, axs


def prepare_plot_data(wind_pickle_path, pload_pickle_path, wp_key="wp5",
                      vchar_col="v_char", demand_col="RT_Demand"):
    """
    Full data-preparation pipeline.

    Parameters
    ----------
    wind_pickle_path : str
        Path to wind pickle.
    pload_pickle_path : str
        Path to load pickle.
    wp_key : str, default "wp5"
        Wind penetration key.
    vchar_col : str, default "v_char"
        Name of v_char column.
    demand_col : str, default "RT_Demand"
        Name of demand column.

    Returns
    -------
    pandas.DataFrame
        Aligned dataframe with columns ['v_char', 'P_load'].
    """
    wind_data = load_wind_data(wind_pickle_path)
    vchar = extract_vchar_series(wind_data, wp_key=wp_key, vchar_col=vchar_col)
    pload = load_pload_data(pload_pickle_path, demand_col=demand_col)
    return align_vchar_and_pload(vchar, pload)


def make_vchar_pload_plot(wind_pickle_path, pload_pickle_path, wp_key="wp5",
                          vchar_col="v_char", demand_col="RT_Demand",
                          bins_x=40, bins_y=40, figsize=(8, 8),
                          title=None, show=True):
    """
    Complete workflow: load data, align overlap, and create the plot.

    Parameters
    ----------
    wind_pickle_path : str
        Path to wind pickle.
    pload_pickle_path : str
        Path to load pickle.
    wp_key : str, default "wp5"
        Wind penetration key.
    vchar_col : str, default "v_char"
        Name of v_char column.
    demand_col : str, default "RT_Demand"
        Name of demand column.
    bins_x, bins_y : int, default 40
        Histogram bins.
    figsize : tuple, default (8, 8)
        Figure size.
    title : str or None
        Title for plot. If None, a default title is created.
    show : bool, default True
        Whether to call plt.show().

    Returns
    -------
    df_plot : pandas.DataFrame
        Aligned plotting dataframe.
    fig : matplotlib.figure.Figure
    axs : dict
        Dictionary of axes.
    """
    df_plot = prepare_plot_data(
        wind_pickle_path=wind_pickle_path,
        pload_pickle_path=pload_pickle_path,
        wp_key=wp_key,
        vchar_col=vchar_col,
        demand_col=demand_col
    )

    if title is None:
        title = f"v_char vs P_load ({wp_key}, overlapping hourly data)"

    fig, axs = create_scatter_hist_figure(
        df_plot=df_plot,
        bins_x=bins_x,
        bins_y=bins_y,
        figsize=figsize,
        title=title
    )

    if show:
        plt.show()

    return df_plot, fig, axs


if __name__ == "__main__":
    wind_pickle = "hourly_windspeeds_by_wp.pkl"
    pload_pickle = "Pload_series.pkl"

    df_plot, fig, axs = make_vchar_pload_plot(
        wind_pickle_path=wind_pickle,
        pload_pickle_path=pload_pickle,
        wp_key="wp5"
    )